### ISSUE TITLE
Integrate JWT for authentication

### ISSUE THREAD

**Issue by srad** [srad/eLogical.API#1]
Currently a session cookie is used to identify individual users and assign internal client-ids to them.

This doesn't work here since the applications are not located on a monolithic server infrastructure.

1. Instead of a session+cookie based approach integrate a JWT authentication.
Clients can anonymously request to get a JWT, i.e. via a route `POST /token/`.

2. This token must always be provided in the client's request header, otherwise request are blocked to all routes.
Either integrate a express based solution or (if better or easier) an Azure based solution

Implementation:

1. Define the route `POST /token` to request a persistent JWT which is valid for x time.
2. Use a node.js environment variable to define the the validity duration of x: `JWT_VALIDITY_DURATION`.
3. Define an express.js middleware which requires that each request - except of `POST /token` and `DELETE /token` need to provide this token for any request to the server (in header as it is standard).
4. Define a route `DELETE /token` which in validates the JWT.

**Comment by Phate94** [comment]
Alright, I've merged the JWT-authentication. Just read the edit on your post and got two questions:
Why the validity-duration and the invalitaion of tokens? Since we don't use a user management and thus, don't need to care about somebody "faking" tokens, this doesn't really matter for our application.
